// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7GPdnKSSox9S_ALBkd_jeUTLb6E70cM',
    appId: '1:270020621605:web:75f4d4d077bae0972696cc',
    messagingSenderId: '270020621605',
    projectId: 'quickchat-51dc7',
    authDomain: 'quickchat-51dc7.firebaseapp.com',
    storageBucket: 'quickchat-51dc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn5yqc8RwbEjXR5rAJVg30jyXHmrO0fYc',
    appId: '1:270020621605:android:5f6eecf5e03491f42696cc',
    messagingSenderId: '270020621605',
    projectId: 'quickchat-51dc7',
    storageBucket: 'quickchat-51dc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS19i-OWYfM2hTFKRq89ca77xKu_ZSaCo',
    appId: '1:270020621605:ios:d2c944216ad11f2a2696cc',
    messagingSenderId: '270020621605',
    projectId: 'quickchat-51dc7',
    storageBucket: 'quickchat-51dc7.appspot.com',
    iosBundleId: 'com.example.quickchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS19i-OWYfM2hTFKRq89ca77xKu_ZSaCo',
    appId: '1:270020621605:ios:272e36d1b10801a52696cc',
    messagingSenderId: '270020621605',
    projectId: 'quickchat-51dc7',
    storageBucket: 'quickchat-51dc7.appspot.com',
    iosBundleId: 'com.example.quickchat.RunnerTests',
  );
}
